// Generates data/books.ts from the blinkist english + persian text files.
// Fetches cover URLs from Open Library (with SVG fallback for misses).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "..", "blinkist-books"); // ~/dev/blinkist-books
const OUT = path.join(ROOT, "data");

// slug -> search title+author for Open Library cover lookup
const BOOKS = [
  { slug: "man-s-search-for-meaning", title: "Man's Search for Meaning", titleFa: "در جستجوی معنا", author: "Viktor Frankl", ol: "mans search for meaning frankl" },
  { slug: "the-alchemist", title: "The Alchemist", titleFa: "کیمیاگر", author: "Paulo Coelho", ol: "the alchemist paulo coelho" },
  { slug: "the-art-of-war", title: "The Art of War", titleFa: "هنر جنگ", author: "Sun Tzu", ol: "art of war sun tzu" },
  { slug: "meditations", title: "Meditations", titleFa: "تأملات", author: "Marcus Aurelius", ol: "meditations marcus aurelius" },
  { slug: "sapiens", title: "Sapiens", titleFa: "ساپینس", author: "Yuval Noah Harari", ol: "sapiens a brief history of humankind harari" },
  { slug: "1984", title: "1984", titleFa: "۱۹۸۴", author: "George Orwell", ol: "1984 george orwell" },
  { slug: "the-little-prince", title: "The Little Prince", titleFa: "شازده کوچولو", author: "Antoine de Saint-Exupéry", ol: "the little prince saint exupery" },
  { slug: "don-quixote", title: "Don Quixote", titleFa: "دون کیشوت", author: "Miguel de Cervantes", ol: "don quixote cervantes" },
  { slug: "one-hundred-years-of-solitude", title: "One Hundred Years of Solitude", titleFa: "صد سال تنهایی", author: "Gabriel García Márquez", ol: "one hundred years of solitude garcia marquez" },
  { slug: "the-republic", title: "The Republic", titleFa: "جمهوری", author: "Plato", ol: "republic plato" },
];

function readPersian(slug) {
  const p = path.join(SRC, "persian", `${slug}.fa.txt`);
  if (!fs.existsSync(p)) return null;
  const text = fs.readFileSync(p, "utf8");
  // strip header lines (# ...) and chunk markers
  const lines = text.split("\n").filter((l) => !l.startsWith("# ") && !l.startsWith("===CHUNK"));
  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trim();
}

async function fetchCover(query) {
  try {
    const url = `https://openlibrary.org/search.json?q=${encodeURIComponent(query)}&limit=1&fields=cover_i,cover_edition_key`;
    const res = await fetch(url, { signal: AbortSignal.timeout(12000) });
    if (!res.ok) return null;
    const j = await res.json();
    const doc = j?.docs?.[0];
    if (!doc) return null;
    const id = doc.cover_i || doc.cover_edition_key;
    if (!id) return null;
    return `https://covers.openlibrary.org/b/id/${id}-L.jpg`;
  } catch {
    return null;
  }
}

function svgFallback(title, author) {
  const t = title.replace(/"/g, "'");
  const a = author.replace(/"/g, "'");
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='400' height='600' viewBox='0 0 400 600'>
  <defs><linearGradient id='g' x1='0' y1='0' x2='0' y2='1'>
    <stop offset='0' stop-color='#1e293b'/><stop offset='1' stop-color='#0f172a'/></linearGradient></defs>
  <rect width='400' height='600' fill='url(#g)'/>
  <rect x='24' y='24' width='352' height='552' fill='none' stroke='#f5d38b' stroke-width='2' rx='6'/>
  <text x='200' y='280' fill='#f5d38b' font-size='26' font-family='serif' text-anchor='middle' font-weight='bold'>${t}</text>
  <text x='200' y='320' fill='#cbd5e1' font-size='16' font-family='sans-serif' text-anchor='middle'>${a}</text>
</svg>`;
  return "data:image/svg+xml;utf8," + encodeURIComponent(svg);
}

async function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const out = [];
  for (const b of BOOKS) {
    const fa = readPersian(b.slug);
    if (!fa) {
      console.error(`MISSING persian for ${b.slug}`);
      continue;
    }
    const cover = (await fetchCover(b.ol)) || svgFallback(b.title, b.author);
    out.push({
      slug: b.slug,
      title: b.title,
      titleFa: b.titleFa,
      author: b.author,
      cover,
      persian: fa,
    });
    console.log(`OK ${b.slug} (cover: ${cover.startsWith("data:") ? "SVG-fallback" : "OpenLibrary"}) ${fa.length} chars`);
  }
  const ts = `// AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.\n` +
    `export type Book = {\n  slug: string;\n  title: string;\n  titleFa: string;\n  author: string;\n  cover: string;\n  persian: string;\n};\n\n` +
    `export const books: Book[] = ${JSON.stringify(out, null, 2)};\n\n` +
    `export function getBook(slug: string): Book | undefined {\n  return books.find((b) => b.slug === slug);\n}\n`;
  fs.writeFileSync(path.join(OUT, "books.ts"), ts);
  console.log(`\nWrote data/books.ts with ${out.length} books.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
